name: web_app
description: Default web application assembly line recipe.
ci_templates:
  - devops/ci/web_app.yml
stages:
  - id: idea_intake
    role: product_manager
    inputs: ["ideas/**"]
    deliverables:
      - "docs/prd/PRODUCT_REQUIREMENTS.md"
    approvals: ["human"]

  - id: architecture
    role: architect
    inputs: ["docs/prd/PRODUCT_REQUIREMENTS.md"]
    deliverables:
      - "api/openapi.yaml"
      - "diagrams/system_architecture.mmd"
      - "docs/blueprint/tech.md"
    approvals: ["human"]

  - id: uiux
    role: uiux_designer
    inputs: ["docs/prd/PRODUCT_REQUIREMENTS.md", "docs/blueprint/tech.md"]
    deliverables:
      - "docs/uiux/style_guide.md"
      - "docs/uiux/wireframes.md"
      - "docs/uiux/user_flows.md"
    approvals: []

  - id: engineering
    role: fullstack_engineer
    inputs:
      ["api/openapi.yaml", "docs/blueprint/tech.md", "ai/code_targets.yaml"]
    deliverables:
      - "src/**"
      - "tests/**"
    approvals: []

  - id: qa
    role: qa_engineer
    inputs: ["tests/**", "api/openapi.yaml", "qa/tests.md"]
    deliverables:
      - "qa/reports/defects.md"
      - "ai/logs/test_runs/latest_report.md"
    approvals: ["human"]

  - id: security
    role: security_engineer
    inputs:
      [
        "security/SECURITY_READINESS.md",
        "devops/devops.yaml",
        "api/openapi.yaml",
      ]
    deliverables:
      - "security/reports/security_audit.md"
      - "security/reports/findings.json"
    approvals: ["human"]

  - id: performance
    role: performance_engineer
    inputs: ["docs/blueprint/tech.md", "docs/observability/**"]
    deliverables:
      - "docs/perf/plan.md"
      - "docs/perf/scripts/**"
    approvals: []

  - id: sre
    role: sre_engineer
    inputs:
      ["docs/observability/**", "devops/devops.yaml", "docs/blueprint/tech.md"]
    deliverables:
      - "docs/observability/dashboards.md"
      - "docs/observability/alerts.md"
      - "docs/observability/slo.md"
    approvals: []

  - id: release
    role: devops_engineer
    inputs:
      [
        "ai/logs/test_runs/latest_report.md",
        "security/reports/security_audit.md",
      ]
    deliverables:
      - "devops/runbooks/deploy.md"
      - "ai/logs/deployments/stage_deploy.md"
    approvals: ["human"]
