name: Mobile App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Validate AutoForge context (planning gates)
        run: |
          cd .autoforge || cd autoforge || true
          npx autoforge validate || node ../.autoforge/scripts/validate_context.js || true
      - name: Test
        run: npm test --if-present

