version: 1
description: DevOps configuration for the Team Todo example.

environments:
  - name: dev
    url: https://todo-dev.example.com
  - name: prod
    url: https://todo.example.com

ci_cd:
  stages:
    - install
    - lint
    - test
    - build
    - deploy
  workflows:
    - path: .github/workflows/ci.yml
      description: Example CI for Todo app

observability:
  logs: JSON (request_id, user_id, latency)
  metrics:
    - rps
    - error_rate
    - latency_p95
  alerts:
    - condition: "error_rate > 1%"
      severity: critical
      channel: pager
